Testlist updates (#547)
* cancel test with unknown action types, use PATH to call apps
* fix cardtype
* increase timeout of snap_example due to longer N250SP simtime
* get parms files from SIMBASE
* separate hdl_nvme_example from hdl_example
Signed-off-by: jkayser <jkayser@de.ibm.com>

diff --git a/hardware/sim/run_sim b/hardware/sim/run_sim
--- a/hardware/sim/run_sim
+++ b/hardware/sim/run_sim
@@ -44,7 +44,7 @@
 
  HOSTNAME=`hostname -s`; echo "hostname=$HOSTNAME arguments=$@"
  TS=`date +%Y%m%d_%H%M%S`; if [ "$TST_TITLE" != "" ];then TS="${TS}_${TST_TITLE}";fi
- export SNAP_ROOT=${PWD%/hardware/sim*};echo "root=$SNAP_ROOT"      # default root, in case its not overwritten
+ export SNAP_ROOT=${PWD%/hardware/sim*};echo "SNAP_ROOT=$SNAP_ROOT"  # default root, in case its not overwritten
  [ -f "${SNAP_ROOT}/snap_env.sh" ]    && . ${SNAP_ROOT}/snap_env.sh
  [ -f "${SNAP_ROOT}/.snap_config.sh" ] && . ${SNAP_ROOT}/.snap_config.sh
  export PATH=$PATH:$SNAP_ROOT/software/tools:$ACTION_ROOT/sw
@@ -135,8 +135,9 @@
  echo "simulator=$SIMULATOR simdir=$SIMDIR simtop=$SIMTOP"
 
  P3=`basename $PWD`
+ SIMBASE=${SNAP_ROOT}/hardware/sim
  if [ "$P3" == "sim" ];then   			# contains sim scripts for GIT
-   echo "in sim_script subdirectory"
+   echo "in sim_script subdirectory $PWD"
    if [ -d "$SIMDIR" ];then cd $SIMDIR;		# ies or xsim directory should have been generated by Vivado scripts (see setup directory)
    else echo "cannot change to $SIMDIR, is model built ?"; exit -1;fi
    ln -s ../run_sim . 2>/dev/null
@@ -144,8 +145,10 @@
 
  P3=`basename $PWD`
  if [ "$P3" == "ies" ] || [ "$P3" == "xsim" ]|| [ "$P3" == "questa" ];then	# contains files from Vivado and sim output, no GIT release
-   echo "prepare simout directory"
-   SIMBASE=$PWD;
+   echo "prepare simout directory from pwd=$PWD p3=$P3"
+#  P3=`basename $PWD`
+#  P4=`dirname $PWD`
+#  echo "pwd=$PWD simbase=$SIMBASE p3=$P3 p4=$P4"
    if [ "$LOCAL" == "1" ];then
      SIMOUT=/data/${IAM}_${TS};mkdir -p $SIMOUT;# use a local name, that can be mapped back to the user
      ln -s $SIMOUT ${TS}_${HOSTNAME}		# and have a symbolic link in AFS, which shows the hostname
@@ -160,7 +163,7 @@
      fi
    fi
    if [ "$SIMDIR" == "ies" ];then
-     cp run_* cds.lib hdl.var $SIMOUT
+#    cp run_* cds.lib hdl.var $SIMOUT
      cp ../nc*.tcl  	      $SIMOUT
 #    cp nc*.log		      $SIMOUT 		# compile output in case of debug questions
    elif [ "$SIMDIR" == "xsim" ];then
@@ -196,7 +199,10 @@
    echo "dont know where I am, leaving $P3 $PWD"; exit 12;
  fi
 
- if [ "$PARM_FILE" != "" ];then cp ${SIMBASE}/${PARM_FILE} pslse.parms;fi       # overwrite with specified parms file
+ if [ "$PARM_FILE" != "" ];then # overwrite with specified parms file
+   if [[ -f ${SIMBASE}/${PARM_FILE} ]];then cp ${SIMBASE}/${PARM_FILE} pslse.parms
+   else echo "file ${SIMBASE}/${PARM_FILE} not found, leaving";exit 11;fi
+ fi
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PSLSE_ROOT/afu_driver/src:$PSLSE_ROOT/libcxl:$SNAP_ROOT/software/lib    # to find libvpi.so and libcxl.so and libsnap.so
  if [[ "$NVME_USED" == "TRUE" && -n "$DENALI" ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DENALI/verilog                                                        # to find libvpi.so and libdenpli.so
@@ -270,8 +276,8 @@
 #  echo "add $VERBOSE to tst_arg $TST_ARG"
    TST_ARG+=" ${VERBOSE}"
  fi
- echo "SNAP_root=$SNAP_ROOT"		 |tee sim.log
- echo "pslse_root=$PSLSE_ROOT"		 |tee -a sim.log
+ echo "pslse_root=$PSLSE_ROOT"		 |tee sim.log
+ echo "SNAP_root= $SNAP_ROOT"		 |tee -a sim.log
  echo "simbase=   $SIMBASE"		 |tee -a sim.log
  echo "simout=    $SIMOUT"		 |tee -a sim.log
  echo "run_sim sim_arg=${SIM_ARG}, tst_arg=${TST_ARG}, AET=$AET"|tee -a sim.log
