run_sim allows list processing
Signed-off-by: jkayser <jkayser@de.ibm.com>

diff --git a/hardware/sim/run_sim b/hardware/sim/run_sim
--- a/hardware/sim/run_sim
+++ b/hardware/sim/run_sim
@@ -35,7 +35,7 @@
  echo "simulator=$SIMULATOR simdir=$SIMDIR simtop=$SIMTOP"
 
  TST_NAME='XTERM'		# default=open xterm
- TST_ARG="-A CAPI"		# default test arguments
+ TST_ARG=""         		# default test arguments
  PARM_FILE=""			# overwrite pslse.parms
  TST_TITLE=""			# suffix for simout_directory to identify testcase
  LOCAL=0			# 1=create simout locally in /data
@@ -53,13 +53,21 @@
 #set -u				# warn for uninitialized variables
 
 # ARGUMENTS #############
+ TS=`date +%Y%m%d_%H%M%S`; if [ "$TST_TITLE" != "" ];then TS="${TS}_${TST_TITLE}";fi
+ if [ ! -d "$USERHOME" ]; then echo "variable USERHOME is not pointing to a directory: $USERHOME, leaving"; exit 11; fi
+ if [ -z $DONUT_ROOT ]; then echo "variable DONUT_ROOT not found, leaving"; exit 11; fi
+ if [ -z $DONUT_SOFTWARE_ROOT ]; then echo "variable DONUT_SOFTWARE_ROOT not found, leaving"; exit 11; fi
+ if [ -z $DONUT_HARDWARE_ROOT ]; then echo "variable DONUT_HARDWARE_ROOT not found, leaving"; exit 11; fi
+ if [ -z $PSLSE_ROOT ]; then echo "variable PSLSE_ROOT not found, leaving"; exit 11; fi
  HOSTNAME=`hostname -s`; echo "hostname=$HOSTNAME arguments=$@"
  runsim_args=$@
  while [[ $# > 0 ]]; do         # consume multiple args per loop with shift
 #  echo "arg=$1"
    case $1 in				
-     -app)		TST_NAME="$2";shift;;	
-     -list)		TST_NAME='LIST';;
+     -app)		TST_NAME="$2";shift	
+     			if [ ! -f $DONUT_SOFTWARE_ROOT/${TST_NAME} ]; then echo "file $DONUT_SOFTWARE_ROOT/${TST_NAME} not found, leaving"; exit 11; fi;;
+     -list)		TST_NAME='LIST';LISTNAME="$2";shift
+     			if [ ! -f ${LIST_NAME} ]; then echo "testlist ${LIST_NAME} not found, leaving"; exit 11; fi;;
      -x|xterm|XTERM)	TST_NAME='XTERM';;
      -quiet)		VERBOSE="";;	
      -verbose)		VERBOSE="-vvv";;	
@@ -86,7 +94,8 @@
      -initx)		SIM_INIT='-ncinitialize x';;
      -h | *) 	printf "Unknown option %s\n" "$1"
 		echo "Usage: $0 -cdemx"
-		echo "  -list        : handwritten testlist with selected testcases"
+		echo "  -app "pgm args": single program including arguments"
+		echo "  -list <file> : handwritten testlist with selected testcases"
 		echo "  -x | xterm   : open xterm for manual testcases(default)"
 		echo "  -t <text>    : title text for XTERM and simout_suffix"
 		echo "  -p <file>    : use different parms file"
@@ -111,10 +120,6 @@
 ##### function declaration
 
 ##### main program
- TS=`date +%Y%m%d_%H%M%S`; if [ "$TST_TITLE" != "" ];then TS="${TS}_${TST_TITLE}";fi
- if [ ! -d "$USERHOME" ]; then echo "variable USERHOME is not pointing to a directory: $USERHOME, leaving"; exit 11; fi
- if [ -z $DONUT_ROOT ]; then echo "variable DONUT_ROOT not found, leaving"; exit 11; fi
- if [ -z $PSLSE_ROOT ]; then echo "variable PSLSE_ROOT not found, leaving"; exit 11; fi
  P3=`basename $PWD`
  if [ "$P3" == "sim" ]; then   			# contains sim scripts for GIT
    echo "in sim_script subdirectory"
@@ -133,6 +138,12 @@
      SIMOUT=$TS; mkdir -p $SIMOUT		# only timestamp, mapping to user is clear
    fi
    unlink latest 2>/dev/null;ln -s $SIMOUT latest; # last generated output directory
+   if [ "$TST_NAME" == "LIST" ];then
+     filename="${LISTNAME%.*}"
+     if [ -f ../${filename}.sh ];then cp ../${filename}* $SIMOUT
+     else echo "cannot find list=${filename}.sh";exit 1
+     fi
+   fi
    if [ "$SIMDIR" == "ies" ];then
      cp run_* cds.lib hdl.var $SIMOUT
      cp ../nc*.tcl  	      $SIMOUT
@@ -173,20 +184,20 @@
  export LD_LIBRARY_PATH=$PSLSE_ROOT/afu_driver/src	# to find libvpi.so
  if [ "$SIMDIR" == "ies" ];then
    if [ "$SIM_INIT" == "" ];then SIM_INIT='-ncinitialize x';fi			# default init value
-#  SIM_OPT='-gui' 		# interactive, stop @cyc0
-#  SIM_OPT='-gui -tcl'		# interactive with simvision
-#  SIM_OPT='-gui -run -tcl' 	# non_interactive, with simvision
-#  SIM_OPT='-run -tcl'		# non_interactive, no exit at end
-   SIM_OPT='-batch'		# -batch overrides -tcl
+#  SIM_ARG='-gui' 		# interactive, stop @cyc0
+#  SIM_ARG='-gui -tcl'		# interactive with simvision
+#  SIM_ARG='-gui -run -tcl' 	# non_interactive, with simvision
+#  SIM_ARG='-run -tcl'		# non_interactive, no exit at end
+   SIM_ARG='-batch'		# -batch overrides -tcl
 #  if [ "$CDS_COVERAGE" == "1" ];then 	# coverage options in ncsim based on envvariable
    if [ -z ${CDS_COVERAGE+x} ];then :	# coverage options in ncsim based on envvariable, works with set -u
 #    echo "env_var CDS_COVERAGE is unset"
    else
      echo "env_var CDS_COVERAGE is set to ${CDS_COVERAGE}"
-     SIM_OPT+=" -covworkdir $SIMBASE/cov_work -covtest $TS"
+     SIM_ARG+=" -covworkdir $SIMBASE/cov_work -covtest $TS"
    fi
 #  VPI_OPT='libvpi.so'
-   SIM_OPT+=" -64bit -input ncrun.tcl"
+   SIM_ARG+=" -64bit -input ncrun.tcl"
    if [ "$VERBOSE" == "-vvvvv" -o "$VERBOSE" == "-vvvvvv" ];then :		# null cmd in case of just comments in clause
      `sed -i "s/ assertion -off -all/#assertion -off -all/g" ncrun.tcl`		# show assertions from cycle 0
    else
@@ -215,18 +226,18 @@
    fi
  elif [ "$SIMDIR" == "xsim" ];then
    SIM_INIT=''		 	# default init value for simulator
-   SIM_OPT=''			# -batch overrides -tcl
+   SIM_ARG=''			# -batch overrides -tcl
    VPI_OPT='libdpi.so'
-   SIM_OPT+=" -t xsrun.tcl"
+   SIM_ARG+=" -t xsrun.tcl"
  elif [ "$SIMDIR" == "questa" ];then
    SIM_INIT=''		 	# default init value for simulator
-   SIM_OPT=''			# -batch overrides -tcl
+   SIM_ARG=''			# -batch overrides -tcl
    VPI_OPT='libdpi.so'
-#  SIM_OPT+=" -t qurun.tcl"
+#  SIM_ARG+=" -t qurun.tcl"
  else echo "cannot set options for simdir=$SIMDIR"; exit 1; fi
 
- SIM_OPT="$SIM_INIT $SIM_OPT"
- TST_ARG+=" -T ${TST_NAME}"
+ SIM_ARG="$SIM_INIT $SIM_ARG"
+#TST_ARG+=" -T ${TST_NAME}"
  if [[ "$TST_ARG" =~ "-v" ]];then
    echo "tst_arg already contains verbose $TST_ARG"
  else
@@ -239,10 +250,10 @@
  echo "pslse=   $PSLSE_ROOT"		|tee -a sim.log
  echo "simbase= $SIMBASE"		|tee -a sim.log
  echo "simout=  $SIMOUT"		|tee -a sim.log
- echo "run_sim arguments=${runsim_args}, sim_opt= ${SIM_OPT}, tst_arg= ${TST_ARG}, AET= $AET"|tee -a sim.log
+ echo "run_sim sim_arg=${SIM_ARG}, tst_arg=${TST_ARG}, AET=$AET"|tee -a sim.log
 
- echo "**** call simulator=$SIMULATOR in background, args=${SIM_OPT}, wait for socket in $SIMULATOR.log->shim_host.dat"|tee -a sim.log &
- $SIMULATOR $SIM_OPT $SIMTOP           |tee -a sim.log &	# sim.log records 1st socket
+ echo "**** call simulator=$SIMULATOR in background, args=${SIM_ARG}, wait for socket in $SIMULATOR.log->shim_host.dat"|tee -a sim.log &
+ $SIMULATOR $SIM_ARG $SIMTOP           |tee -a sim.log &	# sim.log records 1st socket
  SIMLOG_PID=$!	
  SIMLOG_PPID=`ps -ef|grep $SIMLOG_PID |grep tee  |awk '{print $3}'`
  for i in {1..10};do 				# wait for SIM_PID to show up
@@ -300,16 +311,24 @@
    ts0=$(date +%s);failed=0;rc=0
    set -o pipefail 					# highest RC in pipe, if set -o pipefail
    randnum=$((RANDOM%1));
-   echo "**** run $PAR $TST_NAME app timeout=${DDCB_TIMEOUT} seed=${TCL_SEED} randnum=$randnum"|tee stim.log
+   echo "**** run $PAR $TST_NAME app(s) timeout=${DDCB_TIMEOUT} seed=${TCL_SEED} randnum=$randnum tst_arg=$TST_ARG"|tee stim.log
    for i in `seq 1 $PAR`;do					# start testcase
      prc[$i]=0
      if [ "$PAR" == "1" ];then STIMLOG="stim.log";else STIMLOG="stim${i}.log";fi
      if [ "$TST_NAME" == "XTERM" ];then
        xterm -title "testcase window, use >script ${STIMLOG}< to log input" & 	# tee+RC doesnt work here, use script instead
+     elif [ "$TST_NAME" == "LIST" ];then
+       filename="${LISTNAME%.*}"; parfilename="${LISTNAME%.*}${i}";echo "listname=${LISTNAME}"|tee -a stim.log
+        if [ -f "${parfilename}.sh" ]; then
+         sh  ${parfilename}.sh 2>&1|tee -a ${parfilename}.log &
+       elif [ -f  "${filename}.sh" ]; then
+         cp  ${filename}.sh ${parfilename}.sh;
+         sh  ${parfilename}.sh 2>&1|tee -a ${parfilename}.log &
+       else echo "cannot start list for par=$PAR"|tee -a stim.log; fi
      elif [ "$TST_NAME" == "EBERHARD" ];then
        $DONUT_SOFTWARE_ROOT/mmio/app0 -vv 2>&1 |tee -a $STIMLOG &  # for Eberhard
      else
-       $DONUT_SOFTWARE_ROOT/${TST_NAME} -vv 2>&1 |tee -a $STIMLOG &
+       $DONUT_SOFTWARE_ROOT/${TST_NAME} $TST_ARG 2>&1 |tee -a $STIMLOG &
      fi
      pid[$i]=$(jobs -p|tail -n1);
      ts4=$(date +%T); echo "$ts4 app $i started, pid=${pid[$i]}"|tee -a stim.log
@@ -325,16 +344,19 @@
 #    echo "$num jobs running, pids=${array[@]}"|tee -a stim.log
 #    for i in "${!array[@]}"; do echo "element $i = ${array[i]}"|tee -a stim.log ; done
      for i in `seq 1 $PAR`;do
+#      echo "checking app=$i ${pid[$i]}"|tee -a stim.log;
        if [[ "${pid[$i]}" == "0" ]];then :
 #        echo "app=$i already checked"|tee -a stim.log;
        elif [[ "${array[@]}" == *"${pid[$i]}"* ]];then :
 #        echo "app=$i ${pid[$i]} still running"|tee -a stim.log;
        else
+#        echo "wait for pid=${pid[$i]}"|tee -a stim.log;
          wait ${pid[$i]};prc[$i]=$?;				# wait for process to get RC, should have ended already
+#        echo "pid=${pid[$i]} rc=${prc[$i]}"|tee -a stim.log;
          if [ "${prc[$i]}" -ne "0" ];then failed=`expr $failed + 1`;fi
          if [[ ${prc[$i]} > $TCRC ]];then TCRC=${prc[$i]};fi	# collect maximum RC from all apps, return code from xterm always 0
-         ts2=$(date +%s); sec=`expr $ts2 - $ts1`
-         ts4=$(date +%T); echo "$ts4 app $i pid=${pid[$i]} RC=${prc[$i]} after $sec seconds, max_RC=$TCRC"|tee -a stim.log
+         ts2=$(date +%s); sec=`expr $ts2 - $ts1`; ts4=$(date +%T);
+         echo "$ts4 app $i pid=${pid[$i]} RC=${prc[$i]} after $sec seconds, max_RC=$TCRC"|tee -a stim.log
          pid[$i]="0";ts1=$(date +%s); 				# dont wait for this pid anymore, start new timer
        fi
      done
@@ -418,7 +440,9 @@
  if [ "$LOCAL" == "1" ];then
    PERCUSED=`df -k 2>/dev/null|grep '\/data'|tail -n1|awk '{print $5}'`
  else
-   PERCUSED=`fs lq |tail -n1|awk '{print $4}'`	
+   afs_exist=`df|grep AFS|wc -l`; if [ "$afs_exist" == "1" ];then
+     PERCUSED=`fs lq |tail -n1|awk '{print $4}'`	
+   else PERCUSED="N/A";fi
  fi
  USED=`du -sk . |awk '{print $1}'`				
  echo "**** RC=$TCRC parallel=$PAR executed=$EXECUTED failed=$FAILED runtime=$RUNTIME simtime=$SIMTIME cpus=$CPUS speed=$SPEED load=$LOAD local=$LOCAL used_kB=$USED percused=$PERCUSED"
