change run_sim to find the config files and deal with SNAP_ROOT
Signed-off-by: jkayser <jkayser@de.ibm.com>

diff --git a/hardware/sim/run_sim b/hardware/sim/run_sim
--- a/hardware/sim/run_sim
+++ b/hardware/sim/run_sim
@@ -15,32 +15,12 @@
 # limitations under the License.
 #
 ###############################################################################
+##### function declaration
 #
+##### main program
 # entry point for simulation, after model has been built
 #
- if [ -z $SNAP_ROOT ]; then
-   snapdir=$(dirname $(dirname $(dirname $(readlink -f "$BASH_SOURCE"))))
-   if [ -f "$snapdir/.snap_env" ] && [ -f "$snapdir/.snap_config.sh" ]; then
-     . "$snapdir/.snap_env"
-     . "$snapdir/.snap_config.sh"
-   fi
- fi
- if [[ -z $SIMDIR && -z $SIMULATOR ]];then SIMULATOR="ncsim"; fi
- if [[ "$SIMULATOR" == "ncsim" || "$SIMULATOR" == "irun" ]];then
-   if [ -z $CDS_INST_DIR ];then echo "CDS_INST_DIR not defined for ncsim"; exit 1; fi
-   SIMDIR="ies"					# simulation directory generated by vivado
-   if [ -z $SIMTOP ];then SIMTOP="work.top";fi	# default top structure
- elif [ "$SIMULATOR" == "xsim" ];then
-   SIMDIR=$SIMULATOR				# simulation directory generated by vivado
-   if [ -z $SIMTOP ];then SIMTOP="top";fi	# default top structure
- elif [[ "$SIMULATOR" == "questa" || "$SIMDIR" == "questa" ]];then
-   if [ -z $MODELSIM_DIR ];then echo "MODELSIM_DIR not defined for questa"; exit 1; fi
-   SIMDIR="questa"				# simulation directory generated by vivado
-   SIMULATOR="vsim"
-   if [ -z $SIMTOP ];then SIMTOP="top";fi	# default top structure
- else echo "simulator=$SIMULATOR is not supported"; exit 1; fi
- echo "simulator=$SIMULATOR simdir=$SIMDIR simtop=$SIMTOP"
-
+# DEFAULTS #############
  TST_NAME='XTERM'		# default=open xterm
  LISTNAME=""     		# name of testlist
  TST_ARG=""         		# default test arguments
@@ -61,22 +41,23 @@
  EXPLORE=0 			# 1=do action exploration before starting application/list/xterm
 #set -u				# warn for uninitialized variables
 
-# ARGUMENTS #############
+ HOSTNAME=`hostname -s`; echo "hostname=$HOSTNAME arguments=$@"
  TS=`date +%Y%m%d_%H%M%S`; if [ "$TST_TITLE" != "" ];then TS="${TS}_${TST_TITLE}";fi
- if [ -z $SNAP_ROOT ];then echo "variable SNAP_ROOT not found, leaving"; exit 11; fi
+ export SNAP_ROOT=${PWD%/hardware/sim*};echo "root=$SNAP_ROOT"      # default root, in case its not overwritten
+ [ -f "${SNAP_ROOT}/.snap_env" ]       && . ${SNAP_ROOT}/.snap_env.sh
+ [ -f "${SNAP_ROOT}/.snap_config.sh" ] && . ${SNAP_ROOT}/.snap_config.sh
+#if [ -z $SNAP_ROOT ];then echo "variable SNAP_ROOT not found, leaving"; exit 11; fi
  if [ -z $PSLSE_ROOT ];then echo "variable PSLSE_ROOT not found, leaving"; exit 11; fi
 
- SNAP_SOFTWARE_ROOT=$SNAP_ROOT/software
- SNAP_HARDWARE_ROOT=$SNAP_ROOT/hardware
- HOSTNAME=`hostname -s`; echo "hostname=$HOSTNAME arguments=$@"
+# ARGUMENTS #############
  runsim_args=$@
  while [[ $# > 0 ]]; do         # consume multiple args per loop with shift
 #  echo "arg1=$1 arg2=$2"
    case $1 in				
      -app)		TST_NAME="$2";shift
-     			if [[ ! -f ${SNAP_SOFTWARE_ROOT}/${TST_NAME} ]];then echo "file ${SNAP_SOFTWARE_ROOT}/${TST_NAME} not found, leaving";exit 11;fi;;
+     			if [[ ! -f ${SNAP_ROOT}/software/${TST_NAME} ]];then echo "file ${SNAP_ROOT}/software/${TST_NAME} not found, leaving";exit 11;fi;;
      -list)		TST_NAME='LIST';LISTNAME="$2";shift
-     			if [[ ! -f ${LISTNAME} ]];then echo "testlist ${LISTNAME} not found, leaving"; exit 11; fi;;
+     			if [[ ! -f ${SNAP_ROOT}/hardware/sim/${LISTNAME} ]];then echo "testlist ${SNAP_ROOT}/hardware/sim/${LISTNAME} not found, leaving"; exit 11; fi;;
      -x|xterm|XTERM)	TST_NAME='XTERM';;
      -quiet)		VERBOSE="";;	
      -verbose)		VERBOSE="-vvv";;	
@@ -129,9 +110,22 @@
    shift
  done
 
-##### function declaration
+ if [[ -z $SIMDIR && -z $SIMULATOR ]];then SIMULATOR="ncsim"; fi
+ if [[ "$SIMULATOR" == "ncsim" || "$SIMULATOR" == "irun" ]];then
+   if [ -z $CDS_INST_DIR ];then echo "CDS_INST_DIR not defined for ncsim"; exit 1; fi
+   SIMDIR="ies"					# simulation directory generated by vivado
+   if [ -z $SIMTOP ];then SIMTOP="work.top";fi	# default top structure
+ elif [ "$SIMULATOR" == "xsim" ];then
+   SIMDIR=$SIMULATOR				# simulation directory generated by vivado
+   if [ -z $SIMTOP ];then SIMTOP="top";fi	# default top structure
+ elif [[ "$SIMULATOR" == "questa" || "$SIMDIR" == "questa" ]];then
+   if [ -z $MODELSIM_DIR ];then echo "MODELSIM_DIR not defined for questa"; exit 1; fi
+   SIMDIR="questa"				# simulation directory generated by vivado
+   SIMULATOR="vsim"
+   if [ -z $SIMTOP ];then SIMTOP="top";fi	# default top structure
+ else echo "simulator=$SIMULATOR is not supported"; exit 1; fi
+ echo "simulator=$SIMULATOR simdir=$SIMDIR simtop=$SIMTOP"
 
-##### main program
  P3=`basename $PWD`
  if [ "$P3" == "sim" ];then   			# contains sim scripts for GIT
    echo "in sim_script subdirectory"
@@ -139,6 +133,7 @@
    else echo "cannot change to $SIMDIR"; exit -1;fi
    ln -s ../run_sim . 2>/dev/null
  fi
+
  P3=`basename $PWD`
  if [ "$P3" == "ies" ] || [ "$P3" == "xsim" ]|| [ "$P3" == "questa" ];then	# contains files from Vivado and sim output, no GIT release
    echo "prepare simout directory"
@@ -166,18 +161,17 @@
      cp ../qu*.tcl  	      $SIMOUT 2>/dev/null
    else echo "cannot prepare simout for simdir=$SIMDIR"; exit 1; fi
    cd $SIMOUT
-#  ln -s $SNAP_HARDWARE_ROOT/support  support  	# to easier get to waveform signallists
+#  ln -s $SNAP_ROOT/hardware/support  support  	# to easier get to waveform signallists
    if   [ "$SIMDIR" == "ies" ];then
-     ln -s $SNAP_HARDWARE_ROOT/sim/ies/ies        	# point to compiled model
-     ln -s $SNAP_HARDWARE_ROOT/sim/ies/INCA_libs 	# point to compiled model
+     ln -s $SNAP_ROOT/hardware/sim/ies/ies        	# point to compiled model
+     ln -s $SNAP_ROOT/hardware/sim/ies/INCA_libs 	# point to compiled model
      ln -s $DENALI_CUSTOM/runtime denali                # point to denali runtime files
    elif [ "$SIMDIR" == "xsim" ];then
-     ln -s $SNAP_HARDWARE_ROOT/sim/xsim/xsim.dir
+     ln -s $SNAP_ROOT/hardware/sim/xsim/xsim.dir
    elif [ "$SIMDIR" == "questa" ];then
-     ln -s $SNAP_HARDWARE_ROOT/sim/questa/msim
-     ln -s $SNAP_HARDWARE_ROOT/sim/questa/work
+     ln -s $SNAP_ROOT/hardware/sim/questa/msim
+     ln -s $SNAP_ROOT/hardware/sim/questa/work
    else echo "dont know model pointer for simdir=$SIMDIR"; exit 1; fi
-#  ln -s $SNAP_SOFTWARE_ROOT          jobq_software
    cp $PSLSE_ROOT/pslse/pslse.parms   .		# default pslse.parms file
  elif [ "${P3:0:3}" == "201" ] || [ "$P3" == "latest" ];then # already in simout i.e. 20160101_235959
    echo "in simout"
@@ -332,7 +326,7 @@
    echo "**** run $PAR $TST_NAME app(s) timeout=${DDCB_TIMEOUT} seed=${TCL_SEED} randnum=$randnum tst_arg=$TST_ARG"|tee stim.log
    if [ "$EXPLORE" == "1" ];then
      echo "explore actions"|tee -a $STIMLOG
-     $SNAP_SOFTWARE_ROOT/tools/snap_maint 2>&1 |tee -a $STIMLOG
+     $SNAP_ROOT/software/tools/snap_maint 2>&1 |tee -a $STIMLOG
    fi
    for i in `seq 1 $PAR`;do					# start testcase
      prc[$i]=0
@@ -350,9 +344,9 @@
          ./${parfilename}.sh 2>&1|tee -a ${parfilename}.log &
        else echo "cannot start list for par=$PAR"|tee -a stim.log; fi
      elif [ "$TST_NAME" == "EBERHARD" ];then
-       $SNAP_SOFTWARE_ROOT/mmio/app0 -vv 2>&1 |tee -a $STIMLOG &  # for Eberhard
+       $SNAP_ROOT/software/mmio/app0 -vv 2>&1 |tee -a $STIMLOG &  # for Eberhard
      else
-       $SNAP_SOFTWARE_ROOT/${TST_NAME} $TST_ARG 2>&1 |tee -a $STIMLOG &
+       $SNAP_ROOT/software/${TST_NAME} $TST_ARG 2>&1 |tee -a $STIMLOG &
      fi
      pid[$i]=$(jobs -p|tail -n1);
      ts4=$(date +%T); echo "$ts4 app $i started, pid=${pid[$i]}"|tee -a stim.log
@@ -446,8 +440,6 @@
  xil_warnings=`grep -i "error:" sim.log |grep -E "tIS violation|tRCD violation|RST_N goes inactive" |wc -l`;
  if [[ "$xil_warnings" -ne "0" ]]; then echo "$xil_warnings tIS/tRCD/RST_N violations found in sim.log, ignored according to Xilinx AR#61901" |tee -a stim.log;fi
 #echo "**** append msgs from $SIMULATOR.log"|tee -a stim.log; grep -i "error" $SIMULATOR.log|grep -v LOADLB |tee -a stim.log # duplicate info to sim.log
-#cd $SNAP_HARDWARE_ROOT; 	HWVERS=`git log --pretty=format:"%h %ad" -n1 --date=iso|awk '{print $1 " "  $2}'`;cd - >/dev/null
-#cd $SNAP_SOFTWARE_ROOT; 	SWVERS=`git log --pretty=format:"%h %ad" -n1 --date=iso|awk '{print $1 " "  $2}'`;cd - >/dev/null
  cd $SNAP_ROOT;          	SNAPVERS=`git log --pretty=format:"%h %ad" -n1 --date=iso|awk '{print $1 " "  $2}'`;cd - >/dev/null
  if [ "${PSLSE_PID}." != "." ] ;then			# variable exists, PSLSE started
    echo "**** append msgs from pslse.log"|tee -a stim.log; grep -i "error" pslse.log|tee -a stim.log
