Config: Including .snap_env.sh and .snap_config.sh in hardware/Makefile
Signed-off-by: Sven Boekholt <boekholt@de.ibm.com>

diff --git a/hardware/Makefile b/hardware/Makefile
--- a/hardware/Makefile
+++ b/hardware/Makefile
@@ -19,14 +19,20 @@
 ############################################################################
 
 ## Variables required by other scripts.
-## If SNAP_ROOT is not set, we assume that we are in the hardware directory.
+## This Makefile is contained in the hardware directory.
 ## So, the root directory is one level above.
 ##
-export SNAP_ROOT ?= $(abspath ..)
+export SNAP_ROOT=$(abspath ..)
 export SNAP_HARDWARE_ROOT=$(SNAP_ROOT)/hardware
 export LOGS_DIR=$(SNAP_HARDWARE_ROOT)/logs
 
--include $(SNAP_ROOT)/.snap_config.cflags
+snap_config_cflags = $(SNAP_ROOT)/.snap_config.cflags
+snap_config_sh     = $(SNAP_ROOT)/.snap_config.sh
+snap_env_sh        = $(SNAP_ROOT)/.snap_env.sh
+
+-include $(snap_config_cflags)
+-include $(snap_config_sh)
+-include $(snap_env_sh)
 
 ifeq "$(FPGACARD)" "KU3"
 	export DDR3_USED=$(SDRAM_USED)
@@ -60,6 +66,8 @@ SNAP_HDL_CORE=$(SNAP_HARDWARE_ROOT)/hdl/core
 SNAP_HDL_HLS=$(SNAP_HARDWARE_ROOT)/hdl/hls
 SNAP_SIM_CORE=$(SNAP_HARDWARE_ROOT)/sim/core
 
+SNAP_SIMULATORS += irun xsim
+
 SNAP_PP_FILES=$(SNAP_HDL_CORE)/psl_accel.vhd \
               $(SNAP_HDL_CORE)/snap_core.vhd \
               $(SNAP_HDL_CORE)/mmio.vhd
@@ -83,20 +91,17 @@ SNAP_BASE_DCP=$(DCP_ROOT)/snap_static_region_bb.dcp
 #      due to missing dependencies between the different targets.
 #
 
-.PHONY: all clean gitclean check_snap_settings check_denali model action_hw action_sw software pslse prepare_environment create_environment config patch_version patch_NVMe image cloud_base cloud_image cloud_action cloud_merge snap_config snap_config_start xsim irun questa
+.PHONY: all snap_env snap_config check_snap_settings check_simulator check_denali prepare_build snap_preprocess_start snap_preprocess patch_version patch_NVMe action_hw create_environment config_start config image cloud_base cloud_action cloud_merge pslse software action_sw model xsim irun questa clean gitclean
 
 all: config model image
 
+snap_env:
+	@$(MAKE) -C ${SNAP_ROOT} snap_env
+
+snap_config:
+	@$(MAKE) -C $(SNAP_ROOT) snap_config 
+
 check_snap_settings:
-	@if [ ! -d "$(SNAP_HARDWARE_ROOT)" ]; then \
-		echo "SNAP_HARDWARE_ROOT does not point to a directory."; \
-		echo "Please source snap_settings before calling make!"; \
-		exit 1; \
-	fi
-	@if [ $(SIMULATOR) != "irun" ] && [ $(SIMULATOR) != "xsim" ] && [ $(SIMULATOR) != "questa" ];then \
-		echo "unknown simulator=$SIMULATOR"; \
-		exit 1; \
-	fi
 	@if [ -z `which git 2> /dev/null` ]; then \
 		echo "The SNAP framework make process relies on git."; \
 		echo "Please make sure that you have installed git and that"; \
@@ -104,13 +109,22 @@ check_snap_settings:
 		exit 1; \
 	fi
 	@cd $(SNAP_HARDWARE_ROOT); if [ -z `git describe HEAD 2> /dev/null` ]; then \
-		echo "$(SNAP_HARDWARE_ROOT) (SNAP_HARDWARE_ROOT) does not belong to a git repository."; \
-		echo "Please check out the SNAP framework as git clone from git@github.com:open-power/donut.git"; \
+		echo "$(SNAP_HARDWARE_ROOT) does not belong to a git repository."; \
+		echo "Please check out the SNAP framework as git clone from git@github.com:open-power/snap.git"; \
 		exit 1; \
+	fi
+	@if [ ! -e $(snap_env_sh) ]; then \
+		echo "Missing snap environment setup file \"$(snap_env_sh)\""; \
+		echo "Please make sure that the snap environment is prepared by calling 'make snap_env'"; \
+	fi
+	@if [ ! -e $(snap_config_sh) ]; then \
+		echo "Missing snap config setup file \"$(snap_config_sh)\""; \
+		echo "Please make sure that the snap configuration is prepared by calling 'make snap_config'"; \
 	fi
 	@if [ -z $(FPGACARD) ] || [ -z $(SDRAM_USED) ] || [ -z $(ILA_DEBUG) ] || [ -z $(NUM_OF_ACTIONS) ] || [ -z $(ACTION_ROOT) ] || [ -z $(PSL_DCP) ]; then \
 		echo "Missing one or more environment  variables"; \
-		echo "Please make sure all of the following variables are prepared!"; \
+		echo "Please make sure that all of the following variables are prepared!"; \
+		echo "(e.g. by calling 'make snap_env')"; \
 		echo "FPGACARD:       $(FPGACARD)"; \
 		echo "PSL_DCP :       $(PSL_DCP)"; \
 		echo "ACTION_ROOT:    $(ACTION_ROOT)"; \
@@ -120,7 +134,7 @@ check_snap_settings:
 		exit 1; \
 	fi
 	@if [ `echo "$(ILA_DEBUG)" | tr a-z A-Z` = "TRUE" ] && [ ! -e "$(ILA_SETUP_FILE)" ]; then \
-		echo "ILA_DEBUG is set to ${ILA_DEBUG} but ILA_SETUP_FILE is not pointing to a file!"; \
+		echo "ILA_DEBUG is set to ${ILA_DEBUG} but ILA_SETUP_FILE (\"${ILA_SETUP_FILE}\") is not pointing to a file!"; \
 		exit 1; \
 	fi
 	@echo "=============================================="
@@ -140,9 +154,18 @@ check_snap_settings:
 	@echo "DDRI_USED      = $(DDRI_USED)"
 	@echo "NVME_USED      = $(NVME_USED)"
 	@echo "ILA_DEBUG      = $(ILA_DEBUG)"
+	@if [ `echo "$(ILA_DEBUG)" | tr a-z A-Z` = "TRUE" ]; then \
+		echo "ILA_SETUP_FILE = $(ILA_SETUP_FILE)"; \
+	fi
 	@echo "SIMULATOR      = $(SIMULATOR)"
 	@echo "USE_PRFLOW     = $(USE_PRFLOW)"
 	@echo "=============================================="
+
+check_simulator:
+	@if [ $(SIMULATOR) != "irun" ] && [ $(SIMULATOR) != "xsim" ]; then \
+		echo "unknown simulator=$SIMULATOR"; \
+		exit 1; \
+	fi
 
 check_denali:
 	@if [ $(NVME_USED) = "TRUE" ]; then \
@@ -155,8 +178,8 @@ check_denali:
 		fi \
 	fi
 
-prepare_environment:
-	@echo -e "\t[PREPARE ENVIRONMENT.] start `date`";
+prepare_build:
+	@echo -e "\t[PREPARE BUILD.......] start `date`";
 	@mkdir -p $(BUILD_DIR);
 	@mkdir -p $(BUILD_DIR)/Reports;
 	@mkdir -p $(LOGS_DIR);
@@ -174,10 +197,13 @@ prepare_environment:
 		ln -f -s $(SNAP_HDL_CORE)/psl_fpga_fgt.vhd_source  $(SNAP_HDL_CORE)/psl_fpga.vhd_source; \
 		ln -f -s $(SNAP_HDL_CORE)/psl_accel_fgt.vhd_source $(SNAP_HDL_CORE)/psl_accel.vhd_source; \
 	fi
-	@echo -e "\t[PREPARE ENVIRONMENT.] done `date`";
+	@echo -e "\t[PREPARE BUILD.......] done `date`";
+
+snap_preprocess_start:
+	@echo -e "\t[SNAP PREPROCESS.....] start `date`";
 
 $(SNAP_ROOT)/.snap_config:
-	@echo -e "\tNeed to run \"$(MAKE) -C $(SNAP_ROOT) snap_config\" first"
+	@echo -e "\tNeed to run \"make snap_config\" first"
 
 $(SNAP_PP_FILES): $(SNAP_ROOT)/.snap_config
 	@echo "Creating $@ ..."
@@ -189,11 +215,18 @@ $(SNAP_PP_FILES): $(SNAP_ROOT)/.snap_config
 %.sv: %.sv_source
 	@$(SNAP_HARDWARE_ROOT)/setup/snap_config.sh $@_source $@
 
-snap_config: snap_config_start $(SNAP_PP_FILES) $(SNAP_CONFIG_FILES)
-	@echo -e "\t[CONFIG SNAP CORE....] done `date`";
+snap_preprocess: snap_preprocess_start $(SNAP_PP_FILES) $(SNAP_CONFIG_FILES)
+	@echo -e "\t[SNAP PREPROCESS.....] done `date`";
 
-snap_config_start:
-	@echo -e "\t[CONFIG SNAP CORE....] start `date`";
+patch_version:
+	@echo -e "\t[PATCH...............] SNAP version and build date registers"; \
+	$(SNAP_HARDWARE_ROOT)/setup/patch_version.sh $(SNAP_HDL_CORE) snap_core_types.vhd
+
+patch_NVMe:
+	@if [ -e "$(SNAP_HARDWARE_ROOT)/setup/patch_NVMe.sh" ] && [ $(NVME_USED) = "TRUE" ]; then \
+		cd $(SNAP_HARDWARE_ROOT)/setup && ./patch_NVMe.sh && cd .. ; \
+		echo -e "\t[PATCH...............] NVMe PCIe Root Complex sim. files"; \
+	fi
 
 action_hw:
 	@echo -e "\t[CONFIG ACTION HW....] start `date`";
@@ -209,28 +242,22 @@ action_hw:
 create_environment:
 	@echo -e "\t[CREATE_ENVIRONMENT..] start `date`";
 	@echo -e "\t                        using `vivado -version |grep Vivado`"
-	@cd $(SNAP_HARDWARE_ROOT)/setup                                    && vivado -quiet -mode batch -source create_ip.tcl        -notrace -log $(LOGS_DIR)/create_ip.log         -journal $(LOGS_DIR)/create_ip.jou
-	@if [ $(NVME_USED) = "TRUE" ]; then cd $(SNAP_HARDWARE_ROOT)/setup && vivado -quiet -mode batch -source create_nvme_host.tcl -notrace -log $(LOGS_DIR)/create_nvme_host.log  -journal $(LOGS_DIR)/create_nvme_host.jou; fi
-	@cd $(SNAP_HARDWARE_ROOT)/setup                                    && vivado -quiet -mode batch -source create_framework.tcl -notrace -log $(LOGS_DIR)/create_framework.log  -journal $(LOGS_DIR)/create_framework.jou
+	@cd $(SNAP_HARDWARE_ROOT)/setup                                          && vivado -quiet -mode batch -source create_ip.tcl        -notrace -log $(LOGS_DIR)/create_ip.log         -journal $(LOGS_DIR)/create_ip.jou
+	@if [ $(NVME_USED) = "TRUE" ]; then cd $(SNAP_HARDWARE_ROOT)/setup       && vivado -quiet -mode batch -source create_nvme_host.tcl -notrace -log $(LOGS_DIR)/create_nvme_host.log  -journal $(LOGS_DIR)/create_nvme_host.jou; fi
+	@eval ILA_SETUP_FILE=$(ILA_SETUP_FILE) && cd $(SNAP_HARDWARE_ROOT)/setup && vivado -quiet -mode batch -source create_framework.tcl -notrace -log $(LOGS_DIR)/create_framework.log  -journal $(LOGS_DIR)/create_framework.jou
 	@echo -e "\t[CREATE_ENVIRONMENT..] done `date`"
 
 config_start:
 	@echo -e "\t[CONFIG..............] start `date`"
 
-config: config_start check_snap_settings prepare_environment snap_config action_hw create_environment patch_version patch_NVMe
+config: config_start check_snap_settings prepare_build snap_preprocess action_hw create_environment patch_version patch_NVMe
+	@touch .config_done
 	@echo -e "\t[CONFIG..............] done `date`"
 
-patch_version:
-	@echo -e "\t[PATCH...............] SNAP version and build date registers"; \
-	$(SNAP_HARDWARE_ROOT)/setup/patch_version.sh $(SNAP_HDL_CORE) snap_core_types.vhd
+.config_done:
+	$(MAKE) config
 
-patch_NVMe:
-	@if [ -e "$(SNAP_HARDWARE_ROOT)/setup/patch_NVMe.sh" ] && [ $(NVME_USED) = "TRUE" ]; then \
-		cd $(SNAP_HARDWARE_ROOT)/setup && ./patch_NVMe.sh && cd .. ; \
-		echo -e "\t[PATCH...............] NVMe PCIe Root Complex sim. files"; \
-	fi
-
-image: snap_config patch_version
+image: .config_done check_snap_settings snap_preprocess patch_version
 	@if [ `echo "$(USE_PRFLOW)" | tr a-z A-Z` = "TRUE" ]; then \
 		echo -e "\tMakefile target $@ not allowed for PR flow!"; exit -1; \
 	fi
@@ -239,7 +266,7 @@ image: snap_config patch_version
 	@$(RM) -r .bitstream_name.txt
 	@echo -e "\t[BUILD IMAGE.........] done  `date`"
 
-cloud_base: snap_config patch_version
+cloud_base: .config_done check_snap_settings snap_preprocess patch_version
 	@if [ `echo "$(USE_PRFLOW)" | tr a-z A-Z` != "TRUE" ]; then \
 		echo -e "\tMakefile target $@ is only allowed for PR flow!"; exit -1; \
 	fi
@@ -255,7 +282,7 @@ $(SNAP_BASE_DCP):
 	@echo -e "\tNeed to run cloud_base first"
 	@exit 1
 
-cloud_action: snap_config action_hw patch_version
+cloud_action: config_done check_snap_settings snap_preprocess action_hw patch_version
 	@if [ `echo "$(USE_PRFLOW)" | tr a-z A-Z` != "TRUE" ]; then \
 		echo -e "\tMakefile target $@ is only allowed for PR flow!"; exit -1; \
 	fi
@@ -264,7 +291,7 @@ cloud_action: snap_config action_hw patch_version
 	@cd $(BUILD_DIR) && env CLOUD_RUN=ACTION vivado -quiet -mode batch -source snap_cloud_build.tcl -notrace -log $(LOGS_DIR)/cloud_action.log -journal $(LOGS_DIR)/cloud_action.jou
 	@echo -e "\t[CLOUD ACTION SYNTH..] done  `date`"
 
-cloud_merge: $(SNAP_BASE_DCP) $(SNAP_ACTION_DCP) prepare_environment
+cloud_merge: $(SNAP_BASE_DCP) $(SNAP_ACTION_DCP) prepare_build
 	@if [ `echo "$(USE_PRFLOW)" | tr a-z A-Z` != "TRUE" ]; then \
 		echo -e "\tMakefile target $@ is only allowed for PR flow!"; exit -1; \
 	fi
@@ -272,8 +299,6 @@ cloud_merge: $(SNAP_BASE_DCP) $(SNAP_ACTION_DCP) prepare_environment
 	@echo -e "\t                        using `vivado -version |grep Vivado`"
 	@cd $(BUILD_DIR) && vivado -quiet -mode batch -source snap_cloud_merge.tcl -notrace -log $(LOGS_DIR)/cloud_merge.log -journal $(LOGS_DIR)/cloud_merge.jou
 	@echo -e "\t[CLOUD MERGE ........] done  `date`"
-
-model: action_sw snap_config patch_version $(SIMULATOR)
 
 pslse:
 	@echo -e "\t[COMPILE PSLSE ......] start `date`"
@@ -293,51 +318,29 @@ action_sw: software
 	@$(MAKE) -C $(ACTION_ROOT)/sw        >> $(LOGS_DIR)/compile_sw.log 2>&1
 	@echo -e "\t[COMPILE ACTION SW...] done `date`"
 
-xsim:
-	@echo -e "\t[BUILD xsim..........] start `date`"
-	@if [ ! -d "$(SNAP_HARDWARE_ROOT)/sim/xsim" ];then \
-		vivado -quiet -mode batch -source setup/export_xsim.tcl -notrace -log $(LOGS_DIR)/compile_$(SIMULATOR).log; \
-		$(SNAP_HARDWARE_ROOT)/setup/patch_sim.sh $(SNAP_HARDWARE_ROOT)/sim/xsim top.sh >> $(LOGS_DIR)/compile_$(SIMULATOR).log 2>&1; \
-		cd $(SNAP_HARDWARE_ROOT)/sim/xsim && ln -sf $(PSLSE_ROOT)/afu_driver/src/libdpi.so; \
+$(SNAP_SIMULATORS): .config_done action_sw snap_preprocess patch_version
+	@echo -e "\t[BUILD $@..........] start `date`"
+	@if [ "$(SIMULATOR)" != "$@" ]; then \
+		echo "Error: Makefile target $@ called with SIMULATOR set to \"$(SIMULATOR)\""; \
+		exit 1; \
 	fi
-	@cd $(SNAP_HARDWARE_ROOT)/sim/xsim; \
-	./top.sh >> $(LOGS_DIR)/compile_$(SIMULATOR).log 2>&1; \
+	@if [ ! -d "$(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@)" ];then \
+		vivado -quiet -mode batch -source setup/export_$@.tcl -notrace -log $(LOGS_DIR)/compile_$@.log; \
+		$(SNAP_HARDWARE_ROOT)/setup/patch_sim.sh $(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@) top.sh >> $(LOGS_DIR)/compile_$@.log 2>&1; \
+		cd $(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@) && ln -sf $(PSLSE_ROOT)/afu_driver/src/libdpi.so; \
+	fi
+	@cd $(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@); \
+	./top.sh >> $(LOGS_DIR)/compile_$@.log 2>&1; \
 	if [ $$? -ne 0 ]; then \
-		echo -e "\t                        Error: please look into $(LOGS_DIR)/compile_$(SIMULATOR).log"; exit -1; \
+		echo -e "\t                        Error: please look into $(LOGS_DIR)/compile_$@.log"; exit -1; \
 	fi
-	@echo -e "\t[BUILD xsim..........] done  `date`"
+	@echo -e "\t[BUILD $@..........] done  `date`"
 
-irun: check_denali
-	@echo -e "\t[BUILD irun..........] start `date`"
-	@if [ ! -d "$(SNAP_HARDWARE_ROOT)/sim/ies" ];then \
-		vivado -quiet -mode batch -source setup/export_irun.tcl -notrace -log $(LOGS_DIR)/compile_$(SIMULATOR).log; \
-		$(SNAP_HARDWARE_ROOT)/setup/patch_sim.sh $(SNAP_HARDWARE_ROOT)/sim/ies top.sh >> $(LOGS_DIR)/compile_$(SIMULATOR).log 2>&1; \
-		cd $(SNAP_HARDWARE_ROOT)/sim/ies && ln -sf $(PSLSE_ROOT)/afu_driver/src/libdpi.so; \
-	fi
-	@cd $(SNAP_HARDWARE_ROOT)/sim/ies;\
-	./top.sh >> $(LOGS_DIR)/compile_$(SIMULATOR).log 2>&1; \
-	if [ $$? -ne 0 ]; then \
-		echo -e "\t                        Error: please look into $(LOGS_DIR)/compile_$(SIMULATOR).log"; exit -1; \
-	fi
-	@echo -e "\t[BUILD irun..........] done  `date`"
-
-questa:
-	@echo -e "\t[BUILD questa........] start `date`"
-	@if [ ! -d "$(SNAP_HARDWARE_ROOT)/sim/questa" ];then \
-		vivado -quiet -mode batch -source setup/export_questa.tcl -notrace -log $(LOGS_DIR)/compile_$(SIMULATOR).log; \
-		$(SNAP_HARDWARE_ROOT)/setup/patch_sim.sh $(SNAP_HARDWARE_ROOT)/sim/questa top.sh >> $(LOGS_DIR)/compile_$(SIMULATOR).log 2>&1; \
-		cd $(SNAP_HARDWARE_ROOT)/sim/questa && ln -sf $(PSLSE_ROOT)/afu_driver/src/libdpi.so; \
-	fi
-	@cd $(SNAP_HARDWARE_ROOT)/sim/questa; \
-	./top.sh >> $(LOGS_DIR)/compile_$(SIMULATOR).log 2>&1; \
-	if [ $$? -ne 0 ]; then \
-		echo -e "\t                        Error: please look into $(LOGS_DIR)/compile_$(SIMULATOR).log"; exit -1; \
-	fi
-	@echo -e "\t[BUILD questa........] done  `date`"
+model: check_simulator $(SIMULATOR)
 
 clean:
 	@echo -e "\t[CLEAN ENVIRONMENT...] start `date`"
-	@$(RM)    .setup_environment
+	@$(RM)    .config_done
 	@$(RM) -r $(SNAP_PP_FILES) $(SNAP_CONFIG_FILES) $(SNAP_TMP_FILES) \
 	          $(SNAP_HDL_CORE)/psl_fpga.vhd_source                    \
 	          $(SNAP_HDL_CORE)/psl_accel.vhd_source                   \
@@ -352,8 +355,8 @@ clean:
 	@$(RM) -r logs
 	@echo -e "\t                        action";
 	@$(RM) $(ACTION_ROOT)/hw/vhdl
-	@if [ -e "$(ACTION_ROOT)/Makefile" ]; then          \
-		make -C $(ACTION_ROOT) $@ > /dev/null;      \
+	@if [ -e "$(ACTION_ROOT)/Makefile" ]; then	    \
+		$(MAKE) -C $(ACTION_ROOT) $@ > /dev/null;   \
 		if [ $$? -ne 0 ]; then                      \
 			echo -e "\tError: [make "$@"] failed for action in $(ACTION_ROOT)"; exit -1; \
 		fi                                          \
