Rc nvme sim (#473)
* preparation of nvme simulation from git
* added pcie_endp_model.v, endp_4_pipe32.v will now created directly by endp_4_pipe32.soma, use $DENALI instead of $DENALI_TOOLS
* check pureview output
Signed-off-by: Thomas Fuchs <thomas.fuchs@de.ibm.com>

* SNAP env: Removing check for unused DENALI_CUSTOM
* NVME model: Adding encrypted SOMA file for PCIe PIPE interface
Signed-off-by: Sven Boekholt <boekholt@de.ibm.com>

* Todd confirms that it is ok to release pcie_endp_model.v to git
Signed-off-by: Todd Greenfield <toddg@us.ibm.com>

diff --git a/hardware/Makefile b/hardware/Makefile
--- a/hardware/Makefile
+++ b/hardware/Makefile
@@ -68,12 +68,13 @@ BUILD_DIR=$(SNAP_HARDWARE_ROOT)/build
 SNAP_HDL_CORE=$(SNAP_HARDWARE_ROOT)/hdl/core
 SNAP_HDL_HLS=$(SNAP_HARDWARE_ROOT)/hdl/hls
 SNAP_SIM_CORE=$(SNAP_HARDWARE_ROOT)/sim/core
+SNAP_SIM_NVME=$(SNAP_HARDWARE_ROOT)/sim/nvme
 
 SNAP_SIMULATORS += irun xsim
 
-SNAP_PP_FILES=$(SNAP_HDL_CORE)/psl_accel.vhd \
-              $(SNAP_HDL_CORE)/snap_core.vhd \
-              $(SNAP_HDL_CORE)/mmio.vhd
+SNAP_PP_FILES_VHD=$(SNAP_HDL_CORE)/psl_accel.vhd   \
+                  $(SNAP_HDL_CORE)/snap_core.vhd   \
+                  $(SNAP_HDL_CORE)/mmio.vhd        
 
 SNAP_CONFIG_FILES=$(SNAP_HDL_CORE)/psl_fpga.vhd \
                   $(SNAP_HDL_CORE)/psl_accel_types.vhd \
@@ -166,11 +167,10 @@ check_nvme:
 			echo "                        NVMe simulation is not supported for SIMULATOR $(SIMULATOR)"; \
 			exit -1; \
 		fi; \
-		if [ !  -d "$(DENALI_TOOLS)" ] || [ ! -d "$(DENALI_CUSTOM)" ]; then \
-			echo "                        Missing one or more environment variables for NVMe simulation."; \
-			echo "                        Please check the following variables."; \
-			echo "                        DENALI_TOOLS:   $(DENALI_TOOLS)"; \
-			echo "                        DENALI_CUSTOM:  $(DENALI_CUSTOM)"; \
+		if [ !  -d "$(DENALI)" ]; then \
+			echo "                        Missing or invalid environment variable for NVMe simulation."; \
+			echo "                        Please check the setting of:"; \
+			echo "                        DENALI:   $(DENALI)"; \
 			exit -1; \
 		fi \
 	fi
@@ -188,24 +188,18 @@ prepare_build: check_psl_dcp
 	@mkdir -p $(LOGS_DIR);
 	@mkdir -p $(BUILD_DIR)/Images;
 	@mkdir -p $(BUILD_DIR)/Checkpoints;
-	@ln -f -s $(SNAP_HARDWARE_ROOT)/setup/snap_build.tcl         $(BUILD_DIR)/snap_build.tcl;
-	@ln -f -s $(SNAP_HARDWARE_ROOT)/setup/snap_cloud_build.tcl   $(BUILD_DIR)/snap_cloud_build.tcl;
-	@ln -f -s $(SNAP_HARDWARE_ROOT)/setup/snap_cloud_merge.tcl   $(BUILD_DIR)/snap_cloud_merge.tcl;
-	@cp -p $(PSL_DCP)                                            $(BUILD_DIR)/Checkpoints/;
-	@if [ $(FPGACARD) = "KU3" ]; then \
-		ln -f -s $(SNAP_HDL_CORE)/psl_fpga_ku3.vhd_source  $(SNAP_HDL_CORE)/psl_fpga.vhd_source; \
-		ln -f -s $(SNAP_HDL_CORE)/psl_accel_ku3.vhd_source $(SNAP_HDL_CORE)/psl_accel.vhd_source; \
-	fi
-	@if [ $(FPGACARD) = "FGT" ]; then \
-		ln -f -s $(SNAP_HDL_CORE)/psl_fpga_fgt.vhd_source  $(SNAP_HDL_CORE)/psl_fpga.vhd_source; \
-		ln -f -s $(SNAP_HDL_CORE)/psl_accel_fgt.vhd_source $(SNAP_HDL_CORE)/psl_accel.vhd_source; \
-	fi
+	@ln -f -s $(SNAP_HARDWARE_ROOT)/setup/snap_build.tcl          $(BUILD_DIR)/snap_build.tcl;
+	@ln -f -s $(SNAP_HARDWARE_ROOT)/setup/snap_cloud_build.tcl    $(BUILD_DIR)/snap_cloud_build.tcl;
+	@ln -f -s $(SNAP_HARDWARE_ROOT)/setup/snap_cloud_merge.tcl    $(BUILD_DIR)/snap_cloud_merge.tcl;
+	@cp -p $(PSL_DCP)                                             $(BUILD_DIR)/Checkpoints/;
+	@ln -f -s $(SNAP_HDL_CORE)/psl_fpga_`echo "$(FPGACARD)" | tr A-Z a-z`.vhd_source  $(SNAP_HDL_CORE)/psl_fpga.vhd_source;
+	@ln -f -s $(SNAP_HDL_CORE)/psl_accel_`echo "$(FPGACARD)" | tr A-Z a-z`.vhd_source $(SNAP_HDL_CORE)/psl_accel.vhd_source;
 	@echo -e "[PREPARE BUILD.......] done  `date +"%T %a %b %d %Y"`";
 
 snap_preprocess_start:
 	@echo -e "[SNAP PREPROCESS.....] start `date +"%T %a %b %d %Y"`";
 
-$(SNAP_PP_FILES):
+$(SNAP_PP_FILES_VHD):
 	@if [ -e $(snap_config_cflags) ]; then \
 		echo -e "                        generating $(notdir $@)"; \
 	else \
@@ -219,13 +213,22 @@ $(SNAP_PP_FILES):
 	@grep -v "^#" $@_tmp > $@
 	@$(RM) $@_tmp
 
+$(SNAP_SIM_NVME)/endp_4_pipe32.v:
+	@if [ $(SIMULATOR) != "nosim" ] && [ $(NVME_USED) = "TRUE" ]; then \
+	  echo -e "                        generating $(notdir $@)"; \
+	  $(DENALI)/bin/pureview -batch -generate all . -genoutput  $(SNAP_SIM_NVME)/endp_4_pipe32.v $(SNAP_SIM_NVME)/endp_4_pipe32.soma > $(LOGS_DIR)/pureview.log 2>&1; \
+	  if [ $$? -ne 0 ]; then \
+		  echo -e "                        Error: please look into $(LOGS_DIR)/pureview.log"; exit -1; \
+	  fi; \
+	fi
+
 %.vhd: %.vhd_source
 	@$(SNAP_HARDWARE_ROOT)/setup/snap_config.sh $@_source $@
 
 %.sv: %.sv_source
 	@$(SNAP_HARDWARE_ROOT)/setup/snap_config.sh $@_source $@
 
-snap_preprocess: snap_preprocess_start $(SNAP_PP_FILES) $(SNAP_CONFIG_FILES)
+snap_preprocess: snap_preprocess_start $(SNAP_PP_FILES_VHD) $(SNAP_SIM_NVME)/endp_4_pipe32.v $(SNAP_CONFIG_FILES)
 	@echo -e "[SNAP PREPROCESS.....] done  `date +"%T %a %b %d %Y"`";
 
 patch_version:
@@ -350,6 +353,8 @@ $(SNAP_SIMULATORS): check_nvme .hw_config_done action_sw snap_preprocess patch_v
 		vivado -quiet -mode batch -source setup/export_$@.tcl -notrace -log $(LOGS_DIR)/compile_$@.log; \
 		$(SNAP_HARDWARE_ROOT)/setup/patch_sim.sh $(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@) top.sh >> $(LOGS_DIR)/compile_$@.log 2>&1; \
 		cd $(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@) && ln -sf $(PSLSE_ROOT)/afu_driver/src/libdpi.so; \
+	else \
+		$(RM) $(LOGS_DIR)/compile_$@.log; \
 	fi
 	@cd $(SNAP_HARDWARE_ROOT)/sim/$(subst irun,ies,$@); \
 	./top.sh >> $(LOGS_DIR)/compile_$@.log 2>&1; \
@@ -373,9 +378,12 @@ endif
 clean:
 	@echo -e "[CLEAN ENVIRONMENT...] start `date +"%T %a %b %d %Y"`"
 	@$(RM)    .hw_config_done
-	@$(RM) -r $(SNAP_PP_FILES) $(SNAP_CONFIG_FILES) $(SNAP_TMP_FILES) \
-	          $(SNAP_HDL_CORE)/psl_fpga.vhd_source                    \
-	          $(SNAP_HDL_CORE)/psl_accel.vhd_source                   \
+	@$(RM) -r $(SNAP_PP_FILES_VHD)                   \
+                  $(SNAP_SIM_NVME)/endp_4_pipe32.v       \
+                  $(SNAP_CONFIG_FILES)                   \
+                  $(SNAP_TMP_FILES)                      \
+	          $(SNAP_HDL_CORE)/psl_fpga.vhd_source   \
+	          $(SNAP_HDL_CORE)/psl_accel.vhd_source  \
 	          *build
 	@echo -e "                        vivado project";
 	@$(RM) -r viv_project*
