separate calls 2015/2016 for export_simulation in export_irun/ncsim.tcl
Signed-off-by: jkayser <jkayser@de.ibm.com>

diff --git a/hardware/setup/create_environment b/hardware/setup/create_environment
--- a/hardware/setup/create_environment
+++ b/hardware/setup/create_environment
@@ -188,16 +188,24 @@
      ./top.sh >${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log 2>&1; rc=$?;check_rc;cd -
    fi
 
-   if [ $SIMULATOR == "irun" ] || [ $SIMULATOR == "ncsim" ]; then
+   if [ $SIMULATOR == "ncsim" ]; then
+     if [ ! -f ${DONUT_HARDWARE_ROOT}/sim/ies/top.sh ]; then                              # modbld script doesnt exist yet
+       vivado -mode batch -source export_ncsim.tcl       || (echo "error in export_ncsim";exit -1)
+     fi
+     sed -i "s/  simulate/# simulate/g" ${DONUT_HARDWARE_ROOT}/sim/ies/top.sh           # run ncsim up to elaboration, skip execution
+     cd ${DONUT_HARDWARE_ROOT}/sim/ies;dir=.;source=$SIMULATOR
+     ln -sf ${PSLSE_ROOT}/afu_driver/src/libdpi.so 2>/dev/null
+     ./top.sh >${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log 2>&1; rc=$?;check_rc;cd -
+   fi
+
+   if [ $SIMULATOR == "irun" ]; then
      if [ ! -f ${DONUT_HARDWARE_ROOT}/sim/ies/top.sh ]; then                              # modbld script doesnt exist yet
        vivado -mode batch -source export_irun.tcl        || (echo "error in export_irun";exit -1)
-       ## patches for irun.  NOTE: if simulator is not specified, it defaults to ncsim in 2015.4 and irun in 2016.3
-       sed -i "s/93 -relax/93 -elaborate -relax/gI" ${DONUT_HARDWARE_ROOT}/sim/ies/top.sh # run irun up to elaboration, skip execution
-       sed -i "s/  simulate/# simulate/g" ${DONUT_HARDWARE_ROOT}/sim/ies/top.sh           # run ncsim up to elaboration, skip execution
-       if [ -f ${DONUT_HARDWARE_ROOT}/sim/ies/run.f ]; then
-         perl -i.ori -pe 's/(.*\/verilog\/top.v)/ -sv $1/mg' ${DONUT_HARDWARE_ROOT}/sim/ies/run.f                          # compile top.v with system verilog
-         perl -i.ori -pe 'BEGIN{undef $/;} s/(^-makelib.*\n.*glbl.v.*\n.*endlib)//mg' ${DONUT_HARDWARE_ROOT}/sim/ies/run.f # remove glbl.v from compile list
-       fi
+     fi
+     sed -i "s/93 -relax/93 -elaborate -relax/gI" ${DONUT_HARDWARE_ROOT}/sim/ies/top.sh # run irun up to elaboration, skip execution
+     if [ -f ${DONUT_HARDWARE_ROOT}/sim/ies/run.f ]; then
+       perl -i.ori -pe 's/(.*\/verilog\/top.v)/ -sv $1/mg' ${DONUT_HARDWARE_ROOT}/sim/ies/run.f                          # compile top.v with system verilog
+       perl -i.ori -pe 'BEGIN{undef $/;} s/(^-makelib.*\n.*glbl.v.*\n.*endlib)//mg' ${DONUT_HARDWARE_ROOT}/sim/ies/run.f # remove glbl.v from compile list
      fi
      cd ${DONUT_HARDWARE_ROOT}/sim/ies;dir=.;source=$SIMULATOR
      ln -sf ${PSLSE_ROOT}/afu_driver/src/libdpi.so 2>/dev/null
@@ -209,7 +217,7 @@
        vivado -mode batch -source export_questa.tcl        || (echo "error in export_questa";exit -1)
        sed -i "s/  simulate/# simulate/g" ${DONUT_HARDWARE_ROOT}/sim/questa/top.sh        # run up to elaboration, skip execution
      fi
-     cd ${DONUT_HARDWARE_ROOT}/sim/questa;dir=.;source="questa"
+     cd ${DONUT_HARDWARE_ROOT}/sim/questa;dir=.;source=$SIMULATOR
      ln -sf ${PSLSE_ROOT}/afu_driver/src/libdpi.so 2>/dev/null
      ./top.sh >${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log 2>&1; rc=$?;check_rc;cd -
    fi
