add support for questa, fix ncsim -init0 to use -initialize 0

diff --git a/hardware/setup/create_environment b/hardware/setup/create_environment
--- a/hardware/setup/create_environment
+++ b/hardware/setup/create_environment
@@ -49,7 +49,9 @@
 # FUNCTIONS ###################
  function check_rc() {
 #  local i j k
-   echo "compile $source args=$DEBUG $CLEAN pwd=$PWD subdir=$dir RC=$rc";
+           grep -i error ${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log
+   errors=`grep -i error ${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log|wc -l`  # you cannot trust the RC alone, better grep for errors in the log
+   echo "compile $source args=$DEBUG $CLEAN pwd=$PWD subdir=$dir RC=$rc errors=$errors";
    git branch -a >>${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log
    git log --pretty=format:"%h %ad" -n1 --date=iso|awk '{print $1 " "  $2 " " $3}'>>${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log
    if [[ $rc > $maxrc ]];then
@@ -104,7 +106,7 @@
 
  if [[ -z ${AFU_CONNECT_TYPE} || ${SIMULATOR} == "xsim" ]]  ;then AFU_CONNECT_TYPE='DPI'; fi
  if [ -z ${SIMULATOR} ]         ;then SIMULATOR="xsim"; fi
- if [[ "$SIMULATOR" != "ncsim" && "$SIMULATOR" != "xsim" ]];then echo "unknown simulator=$SIMULATOR";maxrc+=1;fi
+ if [[ "$SIMULATOR" != "ncsim" && "$SIMULATOR" != "xsim" && "$SIMULATOR" != "questa" ]];then echo "unknown simulator=$SIMULATOR";maxrc+=1;fi
 
  if [[ $maxrc > 0 ]];then exit;fi
  echo "compile for simulator=$SIMULATOR afu_connnect_type=${AFU_CONNECT_TYPE}"
@@ -173,6 +175,7 @@
  if [ "$CLEAN" == "clean" ];then
    rm -rf sim/ies
    rm -rf sim/xsim
+   rm -rf sim/questa
  fi
  if [ ! -d ${DONUT_HARDWARE_ROOT}/sim/ies ];then
    cd ${DONUT_HARDWARE_ROOT}/setup; echo "run Vivado setup scripts"
@@ -189,6 +192,11 @@
  fi
  if [ -z $SIMULATOR ] || [ $SIMULATOR == "xsim" ]; then
    cd ${DONUT_HARDWARE_ROOT}/sim/xsim;  dir="."   ;
+   ln -sf ${PSLSE_ROOT}/afu_driver/src/libdpi.so 2>/dev/null
+   ./top.sh >${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log 2>&1; rc=$?;check_rc;cd -
+ fi
+ if [ -z $SIMULATOR ] || [ $SIMULATOR == "questa" ]; then
+   cd ${DONUT_HARDWARE_ROOT}/sim/questa;  dir="."   ;
    ln -sf ${PSLSE_ROOT}/afu_driver/src/libdpi.so 2>/dev/null
    ./top.sh >${DONUT_HARDWARE_ROOT}/sim/compile_${source}.log 2>&1; rc=$?;check_rc;cd -
  fi
diff --git a/hardware/sim/run_sim b/hardware/sim/run_sim
--- a/hardware/sim/run_sim
+++ b/hardware/sim/run_sim
@@ -18,22 +18,21 @@
 #
 # entry point for simulation, after model has been built
 #
- if [ -z $SIMDIR ];then
-   if [ -z $SIMULATOR ];then SIMDIR="ies"; SIMULATOR="ncsim";
-   elif [ $SIMULATOR == "ncsim" ];then SIMDIR="ies"
-   elif [ $SIMULATOR == "xsim" ];then SIMDIR="xsim"
-   fi
- fi
+ if [[ -z $SIMDIR && -z $SIMULATOR ]];then SIMULATOR="ncsim"; fi
  if [ "$SIMULATOR" == "ncsim" ];then
    if [ -z $CDS_INST_DIR ]; then echo "CDS_INST_DIR not defined for ncsim"; exit 1; fi
-   SIM_INIT='-ncinitialize x' 			# default init value for simulator
+   SIMDIR="ies"					# simulation directory generated by vivado
    if [ -z $SIMTOP ];then SIMTOP="work.top";fi	# default top structure
  elif [ "$SIMULATOR" == "xsim" ];then
-   SIMDIR=$SIMULATOR
-   SIM_INIT='' 					# default init value for simulator
+   SIMDIR=$SIMULATOR				# simulation directory generated by vivado
+   if [ -z $SIMTOP ];then SIMTOP="top";fi	# default top structure
+ elif [[ "$SIMULATOR" == "questa" || "$SIMDIR" == "questa" ]];then
+   if [ -z $MODELSIM_DIR ]; then echo "MODELSIM_DIR not defined for questa"; exit 1; fi
+   SIMDIR="questa"				# simulation directory generated by vivado
+   SIMULATOR="vsim"
    if [ -z $SIMTOP ];then SIMTOP="top";fi	# default top structure
  else echo "simulator=$SIMULATOR is not supported"; exit 1; fi
- echo "simulator=$SIMULATOR simdir=$SIMDIR simtop=$SIMTOP sim_init=$SIM_INIT"
+ echo "simulator=$SIMULATOR simdir=$SIMDIR simtop=$SIMTOP"
 
  TST_NAME='XTERM'		# default=open xterm
  TST_ARG="-A CAPI"		# default test arguments
@@ -50,6 +49,7 @@
  PAR=1				# number of parallel runs for AFU directed mode
  RNDMASK=0			# frequently change aggravator values with randmask.sh
  TCRC=0				# testcase RC
+ SIM_INIT='' 			# default init value for simulator
 #set -u				# warn for uninitialized variables
 
 # ARGUMENTS #############
@@ -123,7 +123,7 @@
    ln -s ../run_sim . 2>/dev/null
  fi
  P3=`basename $PWD`
- if [ $P3 == "ies" ] || [ $P3 == "xsim" ]; then	# contains files from Vivado and sim output, no GIT release
+ if [ $P3 == "ies" ] || [ $P3 == "xsim" ]|| [ $P3 == "questa" ]; then	# contains files from Vivado and sim output, no GIT release
    echo "prepare simout directory"
    SIMBASE=$PWD;
    if [ "$LOCAL" == "1" ]; then
@@ -133,18 +133,25 @@
      SIMOUT=$TS; mkdir -p $SIMOUT		# only timestamp, mapping to user is clear
    fi
    unlink latest 2>/dev/null;ln -s $SIMOUT latest; # last generated output directory
-   if [ $SIMULATOR == "ncsim" ];then
-     cp run_* cds.lib hdl.var $SIMOUT;
+   if [ $SIMDIR == "ncsim" ];then
+     cp run_* cds.lib hdl.var $SIMOUT
      cp ../nc*.tcl  	      $SIMOUT
 #    cp nc*.log		      $SIMOUT 		# compile output in case of debug questions
-   elif [ "$SIMULATOR" == "xsim" ];then
+   elif [ "$SIMDIR" == "xsim" ];then
      cp ../xs*.tcl  	      $SIMOUT
-   fi
+   elif [ "$SIMDIR" == "questa" ];then
+     cp ../qu*.tcl  	      $SIMOUT 2>/dev/null
+   else echo "cannot prepare simout for simdir=$SIMDIR"; exit 1; fi
    cd $SIMOUT
 #  ln -s $DONUT_HARDWARE_ROOT/support  support  	# to easier get to waveform signallists
-   if [ $SIMULATOR == "ncsim" ];then  ln -s $DONUT_HARDWARE_ROOT/sim/ies/ies        # point to compiled model
-   elif [ $SIMULATOR == "xsim" ];then ln -s $DONUT_HARDWARE_ROOT/sim/xsim/xsim.dir
-   fi
+   if   [ $SIMDIR == "ies" ];    then
+     ln -s $DONUT_HARDWARE_ROOT/sim/ies/ies        # point to compiled model
+   elif [ $SIMDIR == "xsim" ];   then
+     ln -s $DONUT_HARDWARE_ROOT/sim/xsim/xsim.dir
+   elif [ $SIMDIR == "questa" ]; then
+     ln -s $DONUT_HARDWARE_ROOT/sim/questa/msim
+     ln -s $DONUT_HARDWARE_ROOT/sim/questa/work
+   else echo "dont know model pointer for simdir=$SIMDIR"; exit 1; fi
 #  ln -s $DONUT_SOFTWARE_ROOT          jobq_software
    cp $PSLSE_ROOT/pslse/pslse.parms   .		# default pslse.parms file
  elif [ ${P3:0:3} == "201" ] || [ $P3 == "latest" ]; then # already in simout i.e. 20160101_235959
@@ -164,8 +171,8 @@
  if [ "$PARM_FILE" != "" ];then cp ${SIMBASE}/${PARM_FILE} pslse.parms;fi	# overwrite with specified parms file
 
  export LD_LIBRARY_PATH=$PSLSE_ROOT/afu_driver/src	# to find libvpi.so
- if [ $SIMULATOR == "ncsim" ];then
-   SIM_INIT='-ncinitialize x' 	# default init value for simulator
+ if [ $SIMDIR == "ies" ];then
+   if [ $SIM_INIT == "" ];then SIM_INIT='-ncinitialize x';fi			# default init value
 #  SIM_OPT='-gui' 		# interactive, stop @cyc0
 #  SIM_OPT='-gui -tcl'		# interactive with simvision
 #  SIM_OPT='-gui -run -tcl' 	# non_interactive, with simvision
@@ -206,12 +213,17 @@
    else
      `sed -i "s/ input ncinject.tcl/#input ncinject.tcl/g" ncrun.tcl` 		# disable/comment  error injection in ncrun.tcl
    fi
- elif [ $SIMULATOR == "xsim" ];then
+ elif [ $SIMDIR == "xsim" ];then
    SIM_INIT=''		 	# default init value for simulator
    SIM_OPT=''			# -batch overrides -tcl
    VPI_OPT='libdpi.so'
    SIM_OPT+=" -t xsrun.tcl"
- fi
+ elif [ $SIMDIR == "questa" ];then
+   SIM_INIT=''		 	# default init value for simulator
+   SIM_OPT=''			# -batch overrides -tcl
+   VPI_OPT='libdpi.so'
+#  SIM_OPT+=" -t qurun.tcl"
+ else echo "cannot set options for simdir=$SIMDIR"; exit 1; fi
 
  SIM_OPT="$SIM_INIT $SIM_OPT"
  TST_ARG+=" -T ${TST_NAME}"
@@ -230,7 +242,6 @@
 
  echo "**** call simulator=$SIMULATOR in background, args=${SIM_OPT}, wait for socket in $SIMULATOR.log->shim_host.dat"|tee -a sim.log &
  $SIMULATOR $SIM_OPT $SIMTOP           |tee -a sim.log &	# sim.log records 1st socket
-#ncsim $SIM_OPT top:v -loadvpi $VPI_OPT|tee -a sim.log &	
  SIMLOG_PID=$!	
  SIMLOG_PPID=`ps -ef|grep $SIMLOG_PID |grep tee  |awk '{print $3}'`
  for i in {1..10};do 				# wait for SIM_PID to show up
